[2025-10-17T19:40:26.406+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-17T19:40:26.414+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_inference.score_batch manual__2025-10-17T19:40:25.942593+00:00 [queued]>
[2025-10-17T19:40:26.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_inference.score_batch manual__2025-10-17T19:40:25.942593+00:00 [queued]>
[2025-10-17T19:40:26.417+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-10-17T19:40:26.420+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): score_batch> on 2025-10-17 19:40:25.942593+00:00
[2025-10-17T19:40:26.422+0000] {standard_task_runner.py:72} INFO - Started process 376 to run task
[2025-10-17T19:40:26.424+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batch_inference', 'score_batch', 'manual__2025-10-17T19:40:25.942593+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/batch_inference.py', '--cfg-path', '/tmp/tmpf4ymcg94']
[2025-10-17T19:40:26.425+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask score_batch
[2025-10-17T19:40:26.445+0000] {task_command.py:467} INFO - Running <TaskInstance: batch_inference.score_batch manual__2025-10-17T19:40:25.942593+00:00 [running]> on host 161f5a2f5c62
[2025-10-17T19:40:26.477+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_inference' AIRFLOW_CTX_TASK_ID='score_batch' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T19:40:25.942593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T19:40:25.942593+00:00'
[2025-10-17T19:40:26.477+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-17T19:40:26.488+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_inference.py", line 28, in score
    model = load_model("blue")
            ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_inference.py", line 24, in load_model
    with open(path,"rb") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/model_blue.pkl'
[2025-10-17T19:40:26.494+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=batch_inference, task_id=score_batch, run_id=manual__2025-10-17T19:40:25.942593+00:00, execution_date=20251017T194025, start_date=20251017T194026, end_date=20251017T194026
[2025-10-17T19:40:26.500+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-17T19:40:26.500+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task score_batch ([Errno 2] No such file or directory: '/opt/airflow/models/model_blue.pkl'; 376)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_inference.py", line 28, in score
    model = load_model("blue")
            ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batch_inference.py", line 24, in load_model
    with open(path,"rb") as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/models/model_blue.pkl'
[2025-10-17T19:40:26.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-17T19:40:26.536+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T19:40:26.537+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
